from util import *

Import('env')

cwd = GetCurrentDir()

path = [cwd+'/easylogger/inc']
path += [cwd+'/port']
env.PrependUnique(CPPPATH=path)

objs = Glob('easylogger/src/*.c')

objs += Glob('port/*.c')

Return('objs')