import os
from util import *
import config

Import('env')

cwd = GetCurrentDir()

if config.TARGET_PLATFORM == 'linux':

    path = [cwd+'/linux']
    env.PrependUnique(CPPPATH=path)

    objs = Glob('linux/*.c')

    Return('objs')
else:
    objs = []
    Return('objs')